export {default as AccountEdit} from './AccountEdit';
export {default as SignUp} from './SignUp';
export {default as ForgotPassword} from './ForgotPassword';
export {default as ChangePassword} from './ChangePassword';
export {default as Login} from './Login';
export {default as Account} from './Account';
export {default as Home} from './Home';
export {default as Schedule} from './Schedule';
export {default as Courses} from './Courses';
