export const NavConfig = {
  Screens: {
    Home: 'Home',
    Schedule: 'Schedule',
    Courses: 'Courses',
    Login: 'Login',
    ForgotPassword: 'ForgotPassword',
    SignUp: 'SignUp',
    Account: 'Account',
    AccountEdit: 'AccountEdit',
    ChangePassword: 'ChangePassword',
    ChangeTheme: 'ChangeTheme',
    ChangeLanguage: 'ChangeLanguage',
    TutorDetail: 'TutorDetail',
    CourseDetail: 'CourseDetail',
    CourseLesson: 'CourseLesson',
    Booking: 'Booking',
    ReportTutor: 'ReportTutor',
    BecomeTutor1: 'BecomeTutor1',
    BecomeTutor2: 'BecomeTutor2',
    BecomeTutor3: 'BecomeTutor3',
  },
  Stacks: {
    Auth: 'AuthStack',
    Main: 'MainStack',
  },
};
